name: my-bluefin-vm
description: 专为 VMware 定制，集成 v2rayA 网络自治能力的 Bluefin 系统
base-image: ghcr.io/ublue-os/bluefin
image-version: stable

modules:
  - type: script
    snippets:
      - dnf -y copr enable zhullyb/v2rayA
      - echo "net.ipv4.ip_forward = 1" > /etc/sysctl.d/99-ip-forward.conf

  - type: rpm-ostree
    install:
      - v2raya
      - trojan
      - iptables
      - ipset
      - open-vm-tools
      - open-vm-tools-desktop
      - git
      - vim
      - htop
      - fastfetch
      - wget
      - fuse
      - flameshot

  - type: systemd
    system:
      enabled:
        - v2raya.service
        - vmtoolsd.service

  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - com.google.Chrome
        - org.telegram.desktop
        - com.jianguoyun.Nutstore
        - com.visualstudio.code
