name: my-bluefin-vm
description: 专为 VMware 定制，集成 v2rayA 网络自治能力的 Bluefin 系统
base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: script
    snippets:
      - dnf -y copr enable zhullyb/v2rayA

  - type: rpm-ostree
    install:
      - v2ray-core
      - v2raya
      - trojan
      - iptables
      - ipset
      - open-vm-tools
      - open-vm-tools-desktop
      - git
      - vim
      - htop
      - fastfetch
      - wget
      - fuse
      - code
      - flameshot

  - type: systemd
    system:
      enabled:
        - v2raya.service
        - vmtoolsd.service
        - docker.service

  - type: files
    files:
      - source: system/99-ip-forward.conf
        destination: /etc/sysctl.d/99-ip-forward.conf
        data: |
          net.ipv4.ip_forward = 1

  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - com.google.Chrome
        - org.telegram.desktop
        - com.jianguoyun.Nutstore
